name: Publish

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

  # Allow manual triggering of the workflow
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: 'patch'

defaults:
  run:
    shell: bash

permissions:
  contents: read # for checkout

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PACKAGE_NAME: ''
  PACKAGE_VERSION: ''

jobs:
  publish:
    name: 🚀 Publish to Open VSX Registry & Visual Studio Marketplace
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔍 Get package name & version
        run: |
          echo "PACKAGE_NAME=$(node -p -e "require('./package.json').name")" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV

      - name: 📥 Download release asset
        uses: robinraju/release-downloader@v1
        with:
          tag: v${{ env.PACKAGE_VERSION }}
          fileName: ${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}.vsix
          out-file-path: ./

      - name: 🔍 Verify downloaded file
        run: |
          ls -la *.vsix
          if [ ! -f "${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}.vsix" ]; then
            echo "Expected VSIX file not found!"
            exit 1
          fi

      - name: 🌐 Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}.vsix
          skipDuplicate: true

      - name: 🌐 Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}.vsix
          skipDuplicate: true
