name: Publish

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*"

  # Allow manual triggering of the workflow
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read # for checkout

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

env:
  STORE_PATH: ''
  PACKAGE_NAME: ''

jobs:
  publish:
    name: 🚀 Publish to Open VSX Registry & Visual Studio Marketplace
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🛑 Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: 🪄 Installing pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: 🏪 Getting pnpm store directory
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: ♻️ Setting up pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 📥 Installing project dependencies
        run: pnpm install --frozen-lockfile

      - name: 📦 Packaging
        run: pnpm package

      - name: 🔍 Getting package name
        run: echo "PACKAGE_NAME=$(node -p -e "require('./package.json').name")" >> $GITHUB_ENV

      - name: 🌐 Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ${{ env.PACKAGE_NAME }}.vsix
          skipDuplicate: true

      - name: 🌐 Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ env.PACKAGE_NAME }}.vsix
          skipDuplicate: true
